name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript check
        run: pnpm run check

      - name: Lint code
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Build package
        run: pnpm run build

      - name: Verify package integrity
        run: pnpm run prepack

      - name: Update package version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
      
          if [ "$VERSION" != "$CURRENT_VERSION" ]; then
            echo "Updating package.json version from $CURRENT_VERSION → $VERSION"
            pnpm version --no-git-tag-version $VERSION
          else
            echo "Package.json version ($CURRENT_VERSION) already matches release tag ($VERSION). Skipping."
          fi

      - name: Publish to NPM
        run: pnpm publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create package summary
        run: |
          echo "## 📦 Package Published Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Package:** \`remotefunctioncache\`" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${GITHUB_REF_NAME#v}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Registry:** [npmjs.com](https://www.npmjs.com/package/remotefunctioncache)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Install Command" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "pnpm add remotefunctioncache" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
